# using yml file instead of properties is a little bit more structured
spring:
  datasource:
    url: "jdbc:h2:file:./gossip-db"
    password: ""

spring.jpa.hibernate.ddl-auto: update
spring.h2.console.enabled: true

# below is the configuration for the 'dev' profile
# it inherits all from the default profile above, but can also
# override values.
---
spring.profiles: dev
spring.datasource.url: "jdbc:h2:mem:./gossip-db"
# debug sql
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
# modify the web pages, without restarting the backend
spring.resources.static-locations: "file:src/main/resources"

# a profile setup to run on Heroku
---
spring.profiles: heroku
server:
  port: "${PORT}"
spring:
  datasource:
    url: "${JDBC_DATABASE_URL}"
    username: "${JDBC_DATABASE_USERNAME}"
    password: "${JDBC_DATABASE_PASSWORD}"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
